/* Central demo state; independent from effects and DOM. */
(function(root){'use strict';
const tariffs={station:8,mobileBase:15,mobileRadius:5,mobilePerKm:.5,home:1199,reservationMinutes:15};
const stations=[
{id:1,name:'Malecón Escénico',address:'Sector Malecón, Manta',distance:1.4,power:120,free:1,total:1,x:48,y:38},
{id:2,name:'Mall del Pacífico',address:'Sector Barbasquillo, Manta',distance:.8,power:120,free:1,total:1,x:27,y:60},
{id:3,name:'ULEAM Campus Manta',address:'Sector universitario, Manta',distance:2.1,power:120,free:0,total:1,x:47,y:77},
{id:4,name:'Parque Central',address:'Sector Centro, Manta',distance:2.6,power:120,free:0,total:1,x:66,y:53},
{id:5,name:'Aeropuerto Eloy Alfaro',address:'Sector aeropuerto, Manta',distance:4.3,power:90,free:0,total:1,x:81,y:25}
].map(s=>({...s,connector:'CCS2',hours:s.id<3?'08:00–20:00':'Por definir',expansion:s.id>2}));
const homeStates=['Solicitud recibida','Visita programada','Propuesta emitida','Instalación programada','Instalación completada'];
const mobileStates=['confirmed','assigned','enroute','arrived','charging','completed'];
const demoUser=()=>({name:'Mathias',fullName:'Mathias Vargas',email:'mathias@example.com',avatar:'MV',vehicle:'BYD Dolphin',plate:'DEMO-001',capacity:55.4,range:400,connector:'CCS2'});
const initial=()=>({version:2,entered:false,user:demoUser(),battery:62,balance:34.5,active:null,history:[],transactions:[{id:'initial',name:'Saldo inicial de demostración',amount:34.5,date:'Inicio de la demo'}],home:[],theme:'light',seq:0,clockOffset:0,occupied:[],pending:null});
const assert=(ok,message)=>{if(!ok)throw Error(message)};
const now=s=>Date.now()+(s.clockOffset||0),stamp=s=>new Date(now(s)).toLocaleString('es-EC');
const priceMobile=distance=>{assert(Number.isFinite(Number(distance))&&Number(distance)>=0&&Number(distance)<=100,'La distancia demo debe estar entre 0 y 100 km.');const km=Number(distance),extra=Math.max(0,km-5);return {distance:km,base:15,extra,fee:Math.round(extra*.5*100)/100,total:Math.round((15+extra*.5)*100)/100};};
function migrate(saved){assert(saved&&[1,2].includes(saved.version)&&saved.user&&Array.isArray(saved.transactions)&&Array.isArray(saved.history)&&Array.isArray(saved.home)&&Number.isFinite(saved.balance)&&Number.isFinite(saved.battery),'Datos de demostración no válidos.');const s=structuredClone(saved),v=s.version;s.user={...demoUser(),...s.user};if(v===1)s.user={...s.user,name:'Mathias',fullName:'Mathias Vargas',avatar:'MV',email:'mathias@example.com'};s.clockOffset??=0;s.occupied??=[];s.pending??=null;s.home=s.home.map(h=>({...h,step:h.step??0,status:homeStates[h.step??0]}));if(s.active){const a=s.active;a.capacity??=s.user.capacity;a.connector??=s.user.connector;if(a.kind==='station'&&a.status==='reserved')a.expiresAt??=now(s)+900000;if(a.kind==='mobile'){if(v===1&&a.step>=3)a.step++;a.quote??=priceMobile(5);a.status=mobileStates[a.step];}}s.version=2;expire(s);return s;}
function available(s,st){return !st.expansion&&!s.occupied.includes(st.id)&&s.active?.stationId!==st.id?1:0;}
function expire(s){if(s.active?.kind==='station'&&s.active.status==='reserved'&&s.active.expiresAt<=now(s)){s.history.unshift({...s.active,status:'Reserva vencida',price:0,date:stamp(s)});s.active=null;return true;}return false;}
function transact(s,id,name,amount){if(s.transactions.some(t=>t.id===id))return;assert(s.balance+amount>=0,'Saldo insuficiente. Recarga tu billetera de demostración.');s.balance=Math.round((s.balance+amount)*100)/100;s.transactions.unshift({id,name,amount,date:stamp(s)});}
function finish(s,stopped=false){const a=s.active;if(!a)return;transact(s,a.id,a.kind==='station'?'Carga · '+a.name:'Synergy Mobile',-a.price);s.battery=a.battery;s.history.unshift({...a,status:stopped?'Carga detenida':a.kind==='station'?'Carga finalizada':'Servicio completado',date:stamp(s)});s.active=null;}
function transition(s,action,p={}){expire(s);switch(action){
case 'enter':s.entered=true;break;
case 'reserve':{assert(!s.active,'Ya tienes un servicio activo. Finalízalo o cancélalo antes de continuar.');const st=stations.find(x=>x.id===p.id);assert(st&&!st.expansion,'Ubicación propuesta de expansión: no admite reservas.');assert(available(s,st),'Esta estación está ocupada. Selecciona otra estación.');assert(st.connector===s.user.connector,'Conector incompatible. Revisa el vehículo o elige una solución compatible.');const target=Number(p.target??Math.min(100,Math.max(80,s.battery+5)));assert(Number.isInteger(target)&&target>s.battery&&target<=100,'El objetivo debe superar la batería actual y no exceder el 100 %.');assert(s.balance>=8,'Saldo insuficiente. Necesitas USD 8,00.');s.active={id:'service-'+(++s.seq),kind:'station',stationId:st.id,name:st.name,address:st.address,vehicle:s.user.vehicle,capacity:s.user.capacity,connector:s.user.connector,price:8,status:'reserved',start:s.battery,battery:s.battery,target,energy:0,minutes:0,expiresAt:now(s)+900000};s.pending=null;break;}
case 'start':assert(s.active?.kind==='station'&&s.active.status==='reserved','No hay una reserva vigente. Puede haber vencido.');s.active.status='charging';break;
case 'advance':{const a=s.active;assert(a?.kind==='station'&&a.status==='charging','No hay una carga en curso.');a.battery=Math.min(a.target,a.battery+10);a.minutes+=10;a.energy=Number(((a.battery-a.start)*a.capacity/100).toFixed(2));s.battery=a.battery;if(a.battery===a.target)finish(s);break;}
case 'stop':assert(s.active?.status==='charging'&&s.active.kind==='station','No hay una carga que detener.');finish(s,true);break;
case 'mobile':{assert(!s.active,'Ya tienes un servicio activo. Finalízalo o cancélalo antes de continuar.');const quote=priceMobile(p.distance??5);assert(s.user.connector==='CCS2','Conector incompatible con la van demo CCS2. Consulta ayuda.');assert(s.balance>=quote.total,'Saldo insuficiente. Necesitas USD '+quote.total.toFixed(2)+'.');assert(typeof p.address==='string'&&p.address.trim().length>=10,'Escribe una dirección de al menos 10 caracteres, con calle y referencia.');assert(!p.scheduled||(Number.isFinite(Date.parse(p.scheduled))&&Date.parse(p.scheduled)>Date.now()),'Elige una fecha y hora futura.');s.active={id:'service-'+(++s.seq),kind:'mobile',name:'Synergy Mobile',address:p.address.trim(),reference:p.reference||'',quote,scheduled:p.scheduled||null,clockStarted:!p.scheduled,vehicle:s.user.vehicle,capacity:s.user.capacity,connector:s.user.connector,price:quote.total,status:'confirmed',step:0,start:s.battery,battery:s.battery,energy:0,minutes:0};s.pending=null;break;}
case 'scheduleStart':assert(s.active?.kind==='mobile'&&s.active.scheduled&&!s.active.clockStarted,'La fecha simulada ya fue alcanzada.');s.active.clockStarted=true;break;
case 'mobileNext':{const a=s.active;assert(a?.kind==='mobile','No hay una solicitud móvil.');assert(a.clockStarted,'Avanza primero a la fecha programada con el reloj de demostración.');if(p.step!==undefined&&p.step!==a.step)break;a.step++;a.status=mobileStates[a.step];if(a.step===5){a.battery=Math.min(100,a.start+18);a.energy=Number(((a.battery-a.start)*a.capacity/100).toFixed(2));a.minutes=30;finish(s);}break;}
case 'cancel':assert(s.active&&(s.active.kind==='station'?s.active.status==='reserved':s.active.step<4),'No es posible cancelar en este estado.');s.history.unshift({...s.active,status:'Cancelado',price:0,date:stamp(s)});s.active=null;break;
case 'topup':assert([10,20,50].includes(p.amount),'Selecciona un importe válido.');assert(typeof p.id==='string','Operación inválida.');transact(s,p.id,'Recarga simulada',p.amount);break;
case 'home':{if(p.requestId&&s.home.some(h=>h.requestId===p.requestId))break;for(const key of ['name','sector','address','housing','parking','vehicle','time'])assert(typeof p[key]==='string'&&p[key].trim().length>=2,'Completa todos los campos de la evaluación.');s.home.unshift({...p,id:'home-'+(++s.seq),step:0,status:homeStates[0],date:stamp(s),updates:[{status:homeStates[0],date:stamp(s)}]});break;}
case 'homeNext':{const h=s.home.find(h=>h.id===p.id);assert(h&&h.step<4,'Esta solicitud ya está completada.');if(p.step!==undefined&&p.step!==h.step)break;h.step++;h.status=homeStates[h.step];h.updates??=[];h.updates.push({status:h.status,date:stamp(s)});break;}
case 'profile':{assert(!s.active,'Finaliza el servicio activo antes de cambiar el vehículo.');assert(p.name.trim().length>=2&&p.fullName.trim().length>=2&&p.vehicle.trim().length>=2&&p.plate.trim().length>=2,'Completa el perfil de demostración.');assert(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email),'Escribe un correo de ejemplo válido.');assert(Number(p.capacity)>=10&&Number(p.capacity)<=200,'La capacidad demo debe estar entre 10 y 200 kWh.');assert(Number(p.range)>=50&&Number(p.range)<=1000,'La autonomía demo debe estar entre 50 y 1000 km.');assert(['CCS2','CHAdeMO','GB/T'].includes(p.connector),'Selecciona un conector demo válido.');s.user={...s.user,...p,name:p.name.trim(),fullName:p.fullName.trim(),capacity:Number(p.capacity),range:Number(p.range),avatar:p.fullName.trim().split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase()};break;}
case 'occupancy':assert([1,2].includes(p.id)&&s.active?.stationId!==p.id,'No puedes cambiar un punto con un servicio activo.');s.occupied=s.occupied.includes(p.id)?s.occupied.filter(id=>id!==p.id):[...s.occupied,p.id];break;
case 'expireDemo':assert(s.active?.status==='reserved','No hay una reserva pendiente.');s.clockOffset+=900000;expire(s);break;
case 'theme':s.theme=s.theme==='light'?'dark':'light';break;
default:throw Error('Acción desconocida');}return s;}
const api={stations,tariffs,homeStates,mobileStates,initial,migrate,available,expire,now,priceMobile,transition};if(typeof module!=='undefined')module.exports=api;else root.Synergy=api;
})(typeof window!=='undefined'?window:globalThis);
